// Phase 8.1 — Telegram bot ↔ Supabase auth bridge.
//
// Called only by the Telegram bot service (deployed on Railway in Phase 8.2),
// NOT by app clients. Authentication is via the `X-Spoon-Bot-Secret` header
// matching the `TELEGRAM_BOT_SHARED_SECRET` env var on both ends. No JWT.
//
// Body:
//   {
//     token:        string,  // one-time code generated by the app
//     telegram_id:  number,  // Telegram's user id
//     username?:    string,  // Telegram @handle, optional
//   }
//
// On success: marks the token consumed, upserts a `telegram_connections`
// row mapping the user_id → telegram_id, returns `{ connected: true,
// user_id }`. The bot then replies "Connected, @username!" in the chat.
//
// Token lifetime: 10 minutes from creation. Single-use. Replay attempts get
// 409 (already consumed) or 410 (expired).

import {
  createClient,
  type SupabaseClient,
} from 'https://esm.sh/@supabase/supabase-js@2.45.0';
import { handlePreflight } from '../_shared/cors.ts';
import { jsonError, jsonResponse } from '../_shared/errors.ts';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? '';
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
const BOT_SHARED_SECRET = Deno.env.get('TELEGRAM_BOT_SHARED_SECRET') ?? '';

const supabaseAdmin: SupabaseClient | null =
  SUPABASE_URL && SERVICE_ROLE_KEY
    ? createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
        auth: { autoRefreshToken: false, persistSession: false },
      })
    : null;

interface TokenRow {
  id: string;
  user_id: string;
  expires_at: string;
  consumed_at: string | null;
}

Deno.serve(async (req) => {
  const preflight = handlePreflight(req);
  if (preflight) return preflight;

  if (req.method !== 'POST') return jsonError(405, 'method_not_allowed');

  // Auth: shared secret matches what the bot has on Railway. Constant-time
  // string compare doesn't matter much here (the secret is high-entropy and
  // not subject to typical timing attacks against short passwords), but
  // exact-equality keeps the surface tiny.
  const headerSecret = req.headers.get('X-Spoon-Bot-Secret') ?? '';
  if (!BOT_SHARED_SECRET || headerSecret !== BOT_SHARED_SECRET) {
    return jsonError(401, 'unauthorized', 'Invalid bot secret');
  }

  if (!supabaseAdmin) {
    return jsonError(500, 'server_misconfigured', 'Missing Supabase env');
  }

  // Body parse
  let body: { token?: unknown; telegram_id?: unknown; username?: unknown };
  try {
    body = await req.json();
  } catch {
    return jsonError(400, 'bad_request', 'Invalid JSON body');
  }
  const token = typeof body.token === 'string' ? body.token.trim() : '';
  const telegramId = typeof body.telegram_id === 'number'
    ? body.telegram_id
    : Number.parseInt(String(body.telegram_id ?? ''), 10);
  const username = typeof body.username === 'string' ? body.username.trim() : null;

  if (!token) return jsonError(400, 'invalid_input', 'token is required');
  if (!Number.isFinite(telegramId) || telegramId <= 0) {
    return jsonError(400, 'invalid_input', 'telegram_id is required');
  }

  // Token lookup
  const { data: tokenRow, error: tokenErr } = await supabaseAdmin
    .from('telegram_auth_tokens')
    .select('id, user_id, expires_at, consumed_at')
    .eq('token', token)
    .maybeSingle<TokenRow>();

  if (tokenErr) {
    console.error('[telegram-auth] token lookup failed', tokenErr);
    return jsonError(500, 'db_error', 'Could not look up token');
  }
  if (!tokenRow) return jsonError(404, 'token_not_found');
  if (tokenRow.consumed_at) {
    return jsonError(409, 'token_already_used');
  }
  if (new Date(tokenRow.expires_at).getTime() < Date.now()) {
    return jsonError(410, 'token_expired');
  }

  // Mark token consumed first — if the upsert below fails the token is
  // burned and the user must regenerate, but we never end up with a "used"
  // connection row that points at a still-redeemable token.
  const consumeAt = new Date().toISOString();
  const { error: consumeErr } = await supabaseAdmin
    .from('telegram_auth_tokens')
    .update({ consumed_at: consumeAt })
    .eq('id', tokenRow.id)
    .is('consumed_at', null);
  if (consumeErr) {
    console.error('[telegram-auth] consume failed', consumeErr);
    return jsonError(500, 'db_error', 'Could not consume token');
  }

  // Upsert the connection. A user has at most one Telegram account; updating
  // an existing row swaps it out (e.g. user lost the old phone and re-paired).
  const { error: connErr } = await supabaseAdmin
    .from('telegram_connections')
    .upsert(
      {
        user_id: tokenRow.user_id,
        telegram_id: telegramId,
        username,
        connected_at: consumeAt,
      },
      { onConflict: 'user_id' },
    );
  if (connErr) {
    console.error('[telegram-auth] connection upsert failed', connErr);
    return jsonError(500, 'db_error', 'Could not record connection');
  }

  return jsonResponse({ connected: true, user_id: tokenRow.user_id });
});
